apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: change-manifests
spec:
  params:
    - name: git_url
      description: Git repository containing manifest files to update
    - name: git_email
      default: pipeline@k8s.local
    - name: git_name
      default: Tekton Pipeline
    - name: git_manifest_dir
      description: Manifests files dir
    - name: tool_image
      default: cnych/helm-kubectl-curl-git-jq-yq
    - name: image_tag
      description: Deploy docker image tag
    - name: branch
      default: master
  steps:
    - name: git-push
      image: $(params.tool_image)
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-auth
              key: username
              optional: true
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: github-auth
              key: password
              optional: true
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -eu
          git config --global user.email "$(params.git_email)"
          git config --global user.name "$(params.git_name)"
          git clone http://${GIT_USERNAME}:${GIT_PASSWORD}@$(params.git_url) repo
          git checkout ${params.branch}
          cd "repo/$(params.git_manifest_dir)"
          ls -l
          echo old value:
          cat deployment.yaml | yq r - 'spec.template.spec.containers.[0].image'
          echo replacing with new value:
          echo $(params.image_tag)
          yq w --inplace deployment.yaml 'spec.template.spec.containers.[0].image' "$(params.image_tag)"
          echo verifying new value
          yq r deployment.yaml 'spec.template.spec.containers.[0].image'
          if ! git diff-index --quiet HEAD --; then
            git status
            git add .
            git commit -m "image updated by tekton pipeline in change-manifests task"
            git push
          else
              echo "no changes, git repository is up to date"
          fi