apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: checkride-app-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: docker.io/laurelring/checkride
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/LaurelRing2199/speech-to-text-code-pattern.git
        - name: revision
          value: checkride
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: install-dependencies
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value:
            - clean-install
      runAfter:
        - clone-repository
    - name: run-tests
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value:
            - test
        - name: IMAGE
          value: "docker.io/library/node:16.10-alpine@sha256:428c390cd260634e809865d15706a11274cbebff7002bd9975871132c1454bed"
      runAfter:
        - install-dependencies
    - name: build-image
      runAfter:
        - run-tests
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: change-manifests
      runAfter:
        - build-image
      params:
        - name: git_url
          value: https://github.com/LaurelRing2199/speech-to-text-code-pattern.git
        - name: git_email
          value: yuhanlin1994@outlook.com
        - name: git_name
          value: LaurelRing2199
        - name: git_manifest_dir
          value: k8s
        - name: image_tag
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
        - name: branch
          value: checkride
      taskRef:
        kind: Task
        name: change-manifests
      workspaces:
        - name: source
          workspace: pipeline-shared-data
