kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: checkride
    app.openshift.io/vcs-uri: 'https://github.com/LaurelRing2199/speech-to-text-code-pattern.git'
    deployment.kubernetes.io/revision: '3'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"speech-to-text-code-pattern-git:latest","namespace":"yuhan-lin-app"},"fieldPath":"spec.template.spec.containers[?(@.name==\"speech-to-text-code-pattern-git\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: >-
    /apis/apps/v1/namespaces/yuhan-lin-app/deployments/speech-to-text-code-pattern-git
  resourceVersion: '10667530'
  name: speech-to-text-code-pattern-git
  uid: 88a28277-e625-4fdd-90d8-de866db22c1a
  creationTimestamp: '2021-09-24T05:47:44Z'
  generation: 3
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-09-24T05:55:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"speech-to-text-code-pattern-git"}':
                  'f:image': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2021-09-24T06:23:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"speech-to-text-code-pattern-git"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"PORT"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"SPEECH_TO_TEXT_APIKEY"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"SPEECH_TO_TEXT_AUTH_TYPE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"SPEECH_TO_TEXT_URL"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-09-24T06:24:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
  namespace: yuhan-lin-app
  labels:
    app: speech-to-text-code-pattern-git
    app.kubernetes.io/component: speech-to-text-code-pattern-git
    app.kubernetes.io/instance: speech-to-text-code-pattern-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: checkride-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-to-text-code-pattern-git
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: speech-to-text-code-pattern-git
        deploymentconfig: speech-to-text-code-pattern-git
    spec:
      containers:
        - name: speech-to-text-code-pattern-git
          image: >-
            image-registry.openshift-image-registry.svc:5000/yuhan-lin-app/speech-to-text-code-pattern-git@sha256:a86e6cdc7e0aa1cba1fed083eb0358132c46dd08a4f9bfc42f6096a6f8aff4b9
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPEECH_TO_TEXT_AUTH_TYPE
              valueFrom:
                configMapKeyRef:
                  name: checkride-app
                  key: SPEECH_TO_TEXT_AUTH_TYPE
            - name: SPEECH_TO_TEXT_APIKEY
              valueFrom:
                configMapKeyRef:
                  name: checkride-app
                  key: SPEECH_TO_TEXT_APIKEY
            - name: SPEECH_TO_TEXT_URL
              valueFrom:
                configMapKeyRef:
                  name: checkride-app
                  key: SPEECH_TO_TEXT_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: checkride-app
                  key: PORT
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-09-24T05:56:00Z'
      lastTransitionTime: '2021-09-24T05:56:00Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-09-24T06:24:01Z'
      lastTransitionTime: '2021-09-24T05:47:44Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "speech-to-text-code-pattern-git-7667bb546" has successfully
        progressed.
